# Don't define "links" between services.   They aren't necessary and they break load balancing if you later
# scale up the storage nodes.
version: '3.0'
services:
  etcd:
    image: quay.io/coreos/etcd:v2.2.5
    command: >
      -name etcd0
      -advertise-client-urls http://etcd:2379,http://etcd:4001
      -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
      -initial-advertise-peer-urls http://etcd:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster etcd0=http://etcd:2380
      -initial-cluster-state new
  astaire:
    image: sofianinho/astaire
    environment:
      - ADDITIONAL_SHARED_CONFIG
    ports:
      - 22
  chronos:
    image: sofianinho/chronos
    environment:
      - ADDITIONAL_SHARED_CONFIG
    ports:
      - 22
  cassandra:
    sysctls:
       net.ipv6.conf.lo.disable_ipv6: 0
    image: sofianinho/cassandra
    environment:
      - ADDITIONAL_SHARED_CONFIG
    ports:
      - 22
  bono:
    image: sofianinho/bono
    environment:
      - PUBLIC_IP
      - ADDITIONAL_SHARED_CONFIG
    ports:
      - 22
      - "3478:3478"
      - "3478:3478/udp"
      - "5060:5060"
      - "5060:5060/udp"
      - "5062:5062"
  sprout:
    image: sofianinho/sprout
    environment:
      - ADDITIONAL_SHARED_CONFIG
    ports:
      - 22
  homestead:
    image: sofianinho/homestead
    environment:
      - ADDITIONAL_SHARED_CONFIG
    ports:
      - 22
  homestead-prov:
    image: sofianinho/homestead-prov
    environment:
      - ADDITIONAL_SHARED_CONFIG
    ports:
      - 22
  homer:
    image: sofianinho/homer
    environment:
      - ADDITIONAL_SHARED_CONFIG
    ports:
      - 22
  ralf:
    image: sofianinho/ralf
    environment:
      - ADDITIONAL_SHARED_CONFIG
    ports:
      - 22
  ellis:
    image: sofianinho/ellis
    environment:
      - ADDITIONAL_SHARED_CONFIG
    ports:
      - 22
      - "80:80"
